name: youthopia_2022_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  extended_icon_button: ^1.0.0
  awesome_snackbar_content: ^0.0.8
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  email_validator: ^2.1.17

  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  font_awesome_flutter: ^10.2.1
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  sizer: ^2.0.15
  supabase: ^0.3.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.11
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#050705"
  image: assets/youthopia_splash.png

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
